maybe this works

diff --git a/.github/workflows/studio-master.yml b/.github/workflows/studio-master.yml
--- a/.github/workflows/studio-master.yml
+++ b/.github/workflows/studio-master.yml
@@ -31,7 +31,17 @@ jobs:
           # Install Python 3.8
           brew install python@3.8
           # Add Python 3.8 to PATH
-          echo "/usr/local/opt/python@3.8/bin" >> $GITHUB_PATH
+          echo "/opt/homebrew/opt/python@3.8/libexec/bin" >> $GITHUB_PATH
+          export PATH="/opt/homebrew/opt/python@3.8/libexec/bin:$PATH"
+
+    - name: Verify Python Version
+        run: |
+          PYTHON_VERSION=$(python3 --version | cut -d " " -f 2)
+          echo "Installed Python version: $PYTHON_VERSION"
+          if [[ ! $PYTHON_VERSION == 3.8* ]]; then
+            echo "Error: Python version does not start with 3.8"
+            exit 1
+          fi
 
       - name: Install Node.js, NPM and Yarn
         uses: actions/setup-node@v3
